#!/usr/bin/env python3
"""Sample local SVG artwork into configurable square binary C++ icon assets."""

import argparse
import copy
import io
import json
from pathlib import Path
import re
import xml.etree.ElementTree as ET

import cairosvg
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[2]
LUCIDE = ROOT / "freeink-sdk/libs/assets/Icons/lucide"
SAMPLES = 64


def sample_icon(spec, source, threshold, size=11):
    """Rasterize before area sampling, so thin strokes between cell centers survive."""
    root = None
    for layer in spec["layers"]:
        document = ET.parse(source / layer["svg"]).getroot()
        if root is None:
            root = ET.Element(document.tag, document.attrib)
            root.set("color", "black")
            if "fill" in spec:
                root.set("fill", spec["fill"])
            if "stroke_width" in spec:
                root.set("stroke-width", str(spec["stroke_width"]))
        if document.get("viewBox") != root.get("viewBox"):
            raise ValueError("Composed SVGs must share a viewBox")
        elements = list(document)
        parent = root
        if "transform" in layer:
            parent = ET.SubElement(root, "{http://www.w3.org/2000/svg}g", {"transform": layer["transform"]})
        for index in layer.get("elements", range(len(elements))):
            parent.append(copy.deepcopy(elements[index]))
    if root is None:
        raise ValueError("An icon needs at least one SVG layer")
    png = cairosvg.svg2png(bytestring=ET.tostring(root), output_width=size * SAMPLES,
                          output_height=size * SAMPLES)
    alpha = Image.open(io.BytesIO(png)).convert("RGBA").getchannel("A")
    coverage = alpha.resize((size, size), Image.Resampling.BOX)
    level = spec.get("threshold", threshold)
    if not 0 < level < 1:
        raise ValueError("Threshold must be between zero and one")
    return tuple(sum((coverage.getpixel((x, y)) / 255 >= level) << (size - 1 - x)
                     for x in range(size)) for y in range(size))


def comparison(source, output):
    """Compare unchanged source SVGs at multiple grids, always with touching 12px dots."""
    sizes = (7, 9, 11, 13)
    sources = (("SUNNY", "sun.svg"), ("PARTLY CLOUDY", "cloud-sun.svg"), ("RAIN", "cloud-rain.svg"))
    image = Image.new("RGB", (1040, 800), "black")
    draw = ImageDraw.Draw(image)
    font = ImageFont.load_default(size=20)
    draw.text((24, 20), "LUCIDE / ORIGINAL SVG / 12 PX DOTS / NO GAP", font=font, fill="white")
    for column, size in enumerate(sizes):
        left = column * 260
        draw.text((left + 24, 70), f"{size} x {size}  /  {size * 12} px", font=font, fill="white")
        for row, (label, svg) in enumerate(sources):
            matrix = sample_icon({"layers": [{"svg": svg}]}, source, 0.23, size)
            x0 = left + (260 - size * 12) // 2
            y0 = 120 + row * 220 + (156 - size * 12) // 2
            for y, bits in enumerate(matrix):
                for x in range(size):
                    if not bits & (1 << (size - 1 - x)):
                        continue
                    # Same pixel-center circle geometry as DotMatrixView.
                    for dy in range(12):
                        for dx in range(12):
                            if (2 * dx - 11) ** 2 + (2 * dy - 11) ** 2 <= 144:
                                draw.point((x0 + x * 12 + dx, y0 + y * 12 + dy), fill="white")
            draw.text((left + 24, 286 + row * 220), label, font=font, fill="white")
    output.parent.mkdir(parents=True, exist_ok=True)
    image.save(output)


def generate(manifest, source, size=None):
    size = manifest.get("size", 11) if size is None else size
    if not isinstance(size, int) or not 1 <= size <= 16:
        raise ValueError("Grid size must be an integer between 1 and 16")
    namespace = manifest["namespace"]
    if not re.fullmatch(r"[a-zA-Z][a-zA-Z0-9]*(::[a-zA-Z][a-zA-Z0-9]*)*", namespace):
        raise ValueError("Invalid C++ namespace")
    license_text = (LUCIDE / "LICENSE").read_text()
    lines = ["// Generated by tools/generate-dot-icons/generate-dot-icons.py. Do not edit.",
             "// Derived from Lucide SVGs; license follows.",
             *["// " + line for line in license_text.splitlines()], "#pragma once", "",
             '#include "platform/ui/DotMatrix.h"', "", f"namespace {namespace} {{", ""]
    names, matrices = set(), set()
    for spec in manifest["icons"]:
        name = spec["name"]
        if not re.fullmatch(r"[A-Z][a-zA-Z0-9]*", name) or name in names:
            raise ValueError(f"Invalid or duplicate icon name: {name}")
        names.add(name)
        rows = sample_icon(spec, source, manifest.get("threshold", 0.23), size)
        if not any(rows) or rows in matrices:
            raise ValueError(f"Empty or indistinguishable matrix: {name}; adjust sampling")
        matrices.add(rows)
        lines.append("// " + name + ": " + ", ".join(layer["svg"] for layer in spec["layers"]))
        lines.append(f"inline constexpr platform::ui::DotMatrix {name}{{.size = {size}, .rows = {{")
        lines.extend(f"    0b{row:0{size}b}," for row in rows)
        lines.extend(["}};", ""])
    lines.extend([f"}}  // namespace {namespace}", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", type=Path, default=Path(__file__).with_name("weather.json"))
    parser.add_argument("--source", type=Path, default=LUCIDE / "icons")
    parser.add_argument("--output", type=Path, default=ROOT / "src/apps/shell/icons/WeatherDotIcons.h")
    parser.add_argument("--check", action="store_true", help="Check committed output without writing")
    parser.add_argument("--size", type=int, choices=range(1, 17), help="Grid side, overriding manifest size (default 11)")
    parser.add_argument("--compare", type=Path, help="Write a 7/9/11/13 grid comparison PNG, without changing C++")
    args = parser.parse_args()
    try:
        if args.compare:
            comparison(args.source, args.compare)
            print(args.compare.resolve())
            return
        text = generate(json.loads(args.manifest.read_text()), args.source, args.size)
        current = args.output.read_text() if args.output.exists() else None
        if args.check:
            if current != text:
                parser.exit(1, f"Outdated generated file: {args.output}\n")
        elif current != text:
            args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_text(text)
    except (ValueError, KeyError, IndexError, OSError, ET.ParseError) as error:
        parser.exit(1, f"Generation failed: {error}\n")
    print(args.output)


if __name__ == "__main__":
    main()
