// Generated by tools/generate-dot-icons/generate-dot-icons.py. Do not edit.
// Derived from Lucide SVGs; license follows.
// ISC License
// 
// Copyright (c) 2026 Lucide Icons and Contributors
// 
// Permission to use, copy, modify, and/or distribute this software for any
// purpose with or without fee is hereby granted, provided that the above
// copyright notice and this permission notice appear in all copies.
// 
// THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
// WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
// ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
// WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
// ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
// OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
// 
// ---
// 
// The following Lucide icons are derived from the Feather project:
// 
// airplay, alert-circle, alert-octagon, alert-triangle, aperture, arrow-down-circle, arrow-down-left, arrow-down-right, arrow-down, arrow-left-circle, arrow-left, arrow-right-circle, arrow-right, arrow-up-circle, arrow-up-left, arrow-up-right, arrow-up, at-sign, calendar, cast, check, chevron-down, chevron-left, chevron-right, chevron-up, chevrons-down, chevrons-left, chevrons-right, chevrons-up, circle, clipboard, clock, code, columns, command, compass, corner-down-left, corner-down-right, corner-left-down, corner-left-up, corner-right-down, corner-right-up, corner-up-left, corner-up-right, crosshair, database, divide-circle, divide-square, dollar-sign, download, external-link, feather, frown, hash, headphones, help-circle, info, italic, key, layout, life-buoy, link-2, link, loader, lock, log-in, log-out, maximize, meh, minimize, minimize-2, minus-circle, minus-square, minus, monitor, moon, more-horizontal, more-vertical, move, music, navigation-2, navigation, octagon, pause-circle, percent, plus-circle, plus-square, plus, power, radio, rss, search, server, share, shopping-bag, sidebar, smartphone, smile, square, table-2, tablet, target, terminal, trash-2, trash, triangle, tv, type, upload, x-circle, x-octagon, x-square, x, zoom-in, zoom-out
// 
// The MIT License (MIT) (for the icons listed above)
// 
// Copyright (c) 2013-present Cole Bemis
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
#pragma once

#include "platform/ui/DotMatrix.h"

namespace apps::shell::icons {

// Clear: sun.svg
inline constexpr platform::ui::DotMatrix Clear{.size = 11, .rows = {
    0b00000100000,
    0b00000100000,
    0b00100000100,
    0b00001110000,
    0b00011111000,
    0b11011111011,
    0b00011111000,
    0b00001110000,
    0b00100000100,
    0b00000100000,
    0b00000100000,
}};

// PartlyCloudy: cloud-sun.svg
inline constexpr platform::ui::DotMatrix PartlyCloudy{.size = 11, .rows = {
    0b00000100000,
    0b00000100000,
    0b00100000100,
    0b00001110000,
    0b00001011000,
    0b01111001011,
    0b01001100000,
    0b11000111000,
    0b11000001000,
    0b01111111000,
    0b00111110000,
}};

// Cloudy: cloud.svg
inline constexpr platform::ui::DotMatrix Cloudy{.size = 11, .rows = {
    0b00000000000,
    0b00000000000,
    0b00111110000,
    0b01100010000,
    0b11000011110,
    0b11000000011,
    0b11000000011,
    0b01100000011,
    0b00111111110,
    0b00000000000,
    0b00000000000,
}};

// Rain: cloud-rain.svg
inline constexpr platform::ui::DotMatrix Rain{.size = 11, .rows = {
    0b00000000000,
    0b00111100000,
    0b01100010000,
    0b11000011110,
    0b11000000010,
    0b11000000011,
    0b01010001011,
    0b00010101010,
    0b00010101000,
    0b00010101000,
    0b00000100000,
}};

// Thunderstorm: zap.svg
inline constexpr platform::ui::DotMatrix Thunderstorm{.size = 11, .rows = {
    0b00000010000,
    0b00000110000,
    0b00001110000,
    0b00011100000,
    0b00110111110,
    0b01100000110,
    0b01111101100,
    0b00000111000,
    0b00001110000,
    0b00001100000,
    0b00001000000,
}};

// Snow: snowflake.svg
inline constexpr platform::ui::DotMatrix Snow{.size = 11, .rows = {
    0b00000000000,
    0b00011011000,
    0b00111011100,
    0b00011111000,
    0b01101110110,
    0b11111011111,
    0b01101110110,
    0b00011111000,
    0b00111011100,
    0b00011011000,
    0b00000000000,
}};

}  // namespace apps::shell::icons
