"""Pack the supplied boot crop into 1-bit, MSB-first monochrome pixels."""

from pathlib import Path
from PIL import Image

root = Path(__file__).resolve().parents[2]
image = Image.open(root / "assets/boot/wordmark.png").convert("L")
# The supplied binary title has white bridges between its 8 px dot cells.
# Bias cell edges toward black, retaining only the round core of each dot.
# Restrict this treatment to the title so the thin attribution stays intact.
for y in range(4, 60):
    for x in range(image.width):
        dx = (x - 4) % 8 - 3.5
        dy = (y - 4) % 8 - 3.5
        if dx * dx + dy * dy > 3.5 * 3.5:
            image.putpixel((x, y), 0)
width, height = image.size
stride = (width + 7) // 8
packed = bytearray(stride * height)
for y in range(height):
    for x in range(width):
        level = int(image.getpixel((x, y)) >= 230)
        packed[y * stride + x // 8] |= level << (7 - x % 8)
lines = [", ".join(f"0x{byte:02X}" for byte in packed[i:i + 16]) for i in range(0, len(packed), 16)]
header = """#pragma once

#include <cstdint>

// Generated by tools/generate-boot-image/generate.py. Do not hand-edit.
namespace platform::hal::boot {
"""
header += f"inline constexpr int width = {width};\ninline constexpr int height = {height};\n"
header += f"inline constexpr int stride = {stride};\ninline constexpr uint8_t pixels[] = {{\n"
header += "\n".join("    " + line + "," for line in lines)
header += "\n};\n}  // namespace platform::hal::boot\n"
(root / "src/platform/hal/generated/BootImage.h").write_text(header)
print(f"Packed {width} x {height}: {len(packed)} bytes")
