#!/usr/bin/env python3
"""Generate Dayring's 1bpp UI fonts. Requires Pillow and fonttools."""
from pathlib import Path
import math
import subprocess

from PIL import Image, ImageDraw, ImageFont
from fontTools.ttLib import TTFont

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "src/platform/fonts/generated"
SPECS = [
    ("RobotoS", "roboto/Roboto-Regular.ttf", 23),
    ("RobotoM", "roboto/Roboto-Regular.ttf", 28),
    ("RobotoL", "roboto/Roboto-Medium.ttf", 32),
    ("RobotoXL", "roboto/Roboto-Medium.ttf", 40),
    ("Roboto2XL", "roboto/Roboto-Medium.ttf", 46),
    ("NDot2XL", "ndot-57/Ndot57-Regular.ttf", 46),
    ("NDot4XL", "ndot-57/Ndot57-Regular.ttf", 80),
    ("NDot120", "ndot-57/Ndot57-Regular.ttf", 120),
]


def rasterize(font, character):
    left, top, right, bottom = font.getbbox(character)
    width, height = right - left, bottom - top
    image = Image.new("1", (width, height))
    if width and height:
        ImageDraw.Draw(image).text((-left, -top), character, font=font, fill=1)
    pixels = list(image.get_flattened_data())
    data = bytearray()
    for start in range(0, len(pixels), 8):
        byte = 0
        for bit, pixel in enumerate(pixels[start:start + 8]):
            byte |= bool(pixel) << (7 - bit)
        data.append(byte)
    return data, width, height, left, top


def generate(name, source, size):
    path = ROOT / "fonts" / source
    font = ImageFont.truetype(str(path), size)
    with TTFont(path) as ttf:
        supported = ttf.getBestCmap()
    characters = "0123456789:ABCDEFGHIJKLMNOPQRSTUVWXYZ" if size == 120 else "".join(map(chr, range(32, 127)))
    missing = [ch for ch in characters if ord(ch) not in supported]
    if missing:
        raise ValueError(f"{source}: missing characters {missing!r}")
    first, last = ord(min(characters)), ord(max(characters))
    ascent, descent = font.getmetrics()
    cell = math.ceil(max(max(font.getlength(ch), font.getbbox(ch)[2] - font.getbbox(ch)[0]) for ch in characters))
    bitmap, glyphs = bytearray(), []
    for code in range(first, last + 1):
        character = chr(code)
        offset = len(bitmap)
        if character not in characters:
            # BitmapFont requires a contiguous table; reserved entries carry no ink.
            glyphs.append((offset, 0, 0, cell, 0, 0))
            continue
        data, width, height, left, top = rasterize(font, character)
        advance = round(font.getlength(character))
        if size == 120:
            # Keep the separator at its natural width; letters and digits share a cell.
            advance = max(advance, width) if character == ":" else cell
            left = (advance - width) // 2
        glyph = (offset, width, height, advance, left, top - ascent)
        limits = ((0, 65535), (0, 255), (0, 255), (0, 255), (-128, 127), (-128, 127))
        if not all(lo <= value <= hi for value, (lo, hi) in zip(glyph, limits)):
            raise ValueError(f"{name}: glyph {character!r} exceeds SDK metrics: {glyph}")
        bitmap.extend(data)
        glyphs.append(glyph)
    if not 0 < ascent + descent <= 255 or not 0 <= ascent <= 255:
        raise ValueError(f"{name}: line metrics exceed SDK limits")
    lines = ["#pragma once", "", "// Generated by tools/generate-fonts.py; do not edit.",
             f"// Source: fonts/{source}, {size}px, 1bpp.", "", "#include <FreeInkUIFont.h>", "",
             "namespace platform::fonts::generated {", f"inline constexpr uint8_t k{name}Bitmap[] = {{"]
    for index in range(0, len(bitmap), 16):
        lines.append("    " + ", ".join(f"0x{byte:02X}" for byte in bitmap[index:index + 16]) + ",")
    lines.extend(["};", f"inline constexpr freeink::ui::FontGlyph k{name}Glyphs[] = {{"])
    for code, glyph in enumerate(glyphs, first):
        lines.append("    {" + ", ".join(map(str, glyph)) + f"}},  // U+{code:04X}")
    lines.extend(["};", f"inline constexpr freeink::ui::BitmapFont k{name} = {{",
                  f"    k{name}Bitmap, k{name}Glyphs, {first}, {last}, {ascent + descent}, {ascent}, "
                  f"{max(g[1] for g in glyphs)}, {max(g[2] for g in glyphs)}, 1}};",
                  "}  // namespace platform::fonts::generated", ""])
    destination = OUTPUT / f"{name}.h"
    destination.write_text("\n".join(lines))
    subprocess.run(["clang-format", "-i", str(destination)], check=True)
    print(f"{name}: {len(characters)} characters, {len(bitmap)} bitmap bytes, line height {ascent + descent}"
          + (f", alphanumeric advance {cell}px, colon advance {glyphs[ord(':') - first][3]}px, "
             f"HH:MM width {cell * 4 + glyphs[ord(':') - first][3]}px" if size == 120 else ""))


if __name__ == "__main__":
    OUTPUT.mkdir(parents=True, exist_ok=True)
    for spec in SPECS:
        generate(*spec)
